version: "3.9"

services:
  receipt-processor:
    build:
      context: . 
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"  
    volumes:        
        - ./data:/app/data  
    depends_on: []  